// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadApiKey():Promise<string>;

export function Placeholder():Promise<void>;

export function SaveApiKey(arg1:string):Promise<void>;
