// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Placeholder() {
  return window['go']['main']['App']['Placeholder']();
}

export function SaveApiKey(arg1) {
  return window['go']['main']['App']['SaveApiKey'](arg1);
}
