// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function CreateEvent(arg1:string,arg2:string):Promise<db.Event>;

export function DeleteEvent(arg1:number):Promise<void>;

export function GetAPIKey():Promise<string>;

export function ListEvents():Promise<Array<db.Event>>;

export function ListEventsByDate(arg1:string):Promise<Array<db.Event>>;

export function ParseText(arg1:string):Promise<Record<string, string>>;

export function RecognizeSpeech(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveAPIKey(arg1:string):Promise<void>;

export function UpdateEvent(arg1:number,arg2:string,arg3:string):Promise<db.Event>;

export function VoiceCreateEvent(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;
