// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSchedule(arg1) {
  return window['go']['main']['App']['CreateSchedule'](arg1);
}

export function DeleteScheduleByDateAndTitle(arg1, arg2) {
  return window['go']['main']['App']['DeleteScheduleByDateAndTitle'](arg1, arg2);
}

export function DeleteScheduleByID(arg1) {
  return window['go']['main']['App']['DeleteScheduleByID'](arg1);
}

export function DeleteSchedulesByDate(arg1) {
  return window['go']['main']['App']['DeleteSchedulesByDate'](arg1);
}

export function ExportSchedulesCSV(arg1) {
  return window['go']['main']['App']['ExportSchedulesCSV'](arg1);
}

export function ListImportantSchedules() {
  return window['go']['main']['App']['ListImportantSchedules']();
}

export function ListScheduledDatesByMonth(arg1) {
  return window['go']['main']['App']['ListScheduledDatesByMonth'](arg1);
}

export function ListSchedules() {
  return window['go']['main']['App']['ListSchedules']();
}

export function ListSchedulesByDate(arg1) {
  return window['go']['main']['App']['ListSchedulesByDate'](arg1);
}

export function LoadApiKey() {
  return window['go']['main']['App']['LoadApiKey']();
}

export function ParseDeleteIntent(arg1) {
  return window['go']['main']['App']['ParseDeleteIntent'](arg1);
}

export function ParseSchedule(arg1) {
  return window['go']['main']['App']['ParseSchedule'](arg1);
}

export function ParseUpdateIntent(arg1) {
  return window['go']['main']['App']['ParseUpdateIntent'](arg1);
}

export function Placeholder() {
  return window['go']['main']['App']['Placeholder']();
}

export function RecognizeSpeech(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecognizeSpeech'](arg1, arg2, arg3);
}

export function SaveApiKey(arg1) {
  return window['go']['main']['App']['SaveApiKey'](arg1);
}

export function SetScheduleImportant(arg1, arg2) {
  return window['go']['main']['App']['SetScheduleImportant'](arg1, arg2);
}

export function UpdateScheduleByID(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateScheduleByID'](arg1, arg2, arg3, arg4);
}
